name: Build & Test

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Free space
        run: df -h && rm -rf /opt/hostedtoolcache* && df -h

      - name: Checkout Lean Same Branch
        id: lean-same-branch
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: ${{ github.ref }}
          repository: QuantConnect/Lean
          path: Lean

      - name: Checkout Lean Master
        if: steps.lean-same-branch.outcome != 'success'
        uses: actions/checkout@v2
        with:
          repository: QuantConnect/Lean
          path: Lean

      - name: Move Lean
        run: mv Lean ../Lean

      - name: Run Image
        uses: addnab/docker-run-action@v3
        with:
          image: quantconnect/lean:foundation
          options: -v /home/runner/work:/__w --workdir /__w/Lean.DataSource.Polygon/Lean.DataSource.Polygon -e QC_POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }} -e QC_JOB_USER_ID=${{ secrets.JOB_USER_ID }} -e QC_API_ACCESS_TOKEN=${{ secrets.API_ACCESS_TOKEN }} -e QC_JOB_ORGANIZATION_ID=${{ secrets.JOB_ORGANIZATION_ID }}
          shell: bash
          run: |
            # Build
            dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.Polygon.sln
            # Run Tests
            dotnet test ./QuantConnect.Polygon.Tests/bin/Release/QuantConnect.Polygon.Tests.dll